<!-- frontend/src/components/BeforeAfterToggle.vue -->
<template>
  <div v-motion :initial="{ opacity: 0, y: 50 }" :enter="{ opacity: 1, y: 0, transition: { duration: 800, delay: 200 } }" class="w-full max-w-4xl mx-auto my-8 md:my-16 px-4">
    <!-- Header Section -->
    <div class="text-center mb-8 md:mb-12">
      <h2 class="text-3xl sm:text-4xl md:text-5xl font-bold mb-4 md:mb-6 bg-gradient-to-r from-primary via-foreground to-secondary bg-clip-text text-transparent">The Transformation Is Dramatic</h2>
      <p class="text-lg sm:text-xl md:text-2xl text-muted-foreground max-w-3xl mx-auto leading-relaxed">
        Watch boring commit messages become engaging release notes that users love to read.
        <br class="hidden md:block" />
        <span class="text-primary font-semibold">Drag the slider</span> to see the magic happen in real-time.
      </p>
    </div>

    <!-- Image Comparison Slider -->
    <div class="bg-card/60 backdrop-blur-xl rounded-3xl shadow-2xl overflow-hidden border border-border/30 hover:border-primary/20 transition-all duration-500">
      <ImgComparisonSlider class="custom-slider focus:ring-2 focus:ring-primary/50" value="50">
        <img slot="first" :src="beforeImageUrl" alt="Before: Poorly written update notes" class="w-full h-auto" loading="lazy" />
        <img slot="second" :src="afterImageUrl" alt="After: Professional update notes generated by AI" class="w-full h-auto" loading="lazy" />
        <!-- Custom Handle for better visibility -->
        <div slot="handle" class="custom-handle">
          <svg width="50" height="50" viewBox="0 0 50 50" fill="none" xmlns="http://www.w3.org/2000/svg">
            <circle cx="25" cy="25" r="22" fill="#000000" stroke="#ffffff" stroke-width="4" />
            <path d="M18 25L22 25M28 25L32 25" stroke="#ffffff" stroke-width="3" stroke-linecap="round" />
            <path d="M19 22L16 25L19 28M31 22L34 25L31 28" stroke="#ffffff" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" />
          </svg>
        </div>
      </ImgComparisonSlider>

      <!-- Enhanced Labels -->
      <div class="flex justify-between items-center p-6 bg-gradient-to-r from-muted/30 via-card/50 to-muted/30 backdrop-blur-sm">
        <div class="flex items-center text-destructive group">
          <div class="w-8 h-8 bg-destructive/10 rounded-full flex items-center justify-center mr-3 group-hover:bg-destructive/20 transition-colors">
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
            </svg>
          </div>
          <div>
            <span class="font-bold text-lg">Before: Manual Work</span>
            <p class="text-sm text-muted-foreground">Hours of writing, boring results</p>
          </div>
        </div>

        <div class="flex items-center text-green-600 group">
          <div>
            <span class="font-bold text-lg">After: AI Magic</span>
            <p class="text-sm text-muted-foreground">60 seconds, professional output</p>
          </div>
          <div class="w-8 h-8 bg-green-100 rounded-full flex items-center justify-center ml-3 group-hover:bg-green-200 transition-colors">
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
            </svg>
          </div>
        </div>
      </div>
    </div>

    <!-- Disclaimer -->
    <div class="text-center mt-6">
      <div class="max-w-2xl mx-auto flex justify-center items-center text-sm text-muted-foreground/80">
        <i class="fa-solid fa-circle-info text-muted-foreground/60 mr-2"></i>
        <p>
          <strong class="mr-1">Note:</strong>
          The examples shown above are mockups created for demonstration purposes and do not represent actual commit data or real user projects.
        </p>
      </div>
    </div>

    <!-- Enhanced Call to Action -->
    <div class="text-center mt-8 md:mt-12">
      <p class="text-lg sm:text-xl text-muted-foreground mb-4 md:mb-6 font-medium">Why spend hours on release notes when AI can create better ones in seconds?</p>
      <div class="flex flex-col sm:flex-row gap-3 sm:gap-4 justify-center">
        <EnhancedButton variant="primary" size="lg" text="Start Your Free Transformation" @click="goToLogin" />
        <EnhancedButton variant="outline" size="lg" text="Learn the 3-Step Process" @click="scrollToHowItWorks" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ImgComparisonSlider } from '@img-comparison-slider/vue'
import { ref } from 'vue'
import EnhancedButton from '@/components/ui/EnhancedButton.vue'

// Props for customization
interface Props {
  beforeImageUrl?: string
  afterImageUrl?: string
}

const props = withDefaults(defineProps<Props>(), {
  beforeImageUrl: '/before.png',
  afterImageUrl: '/after.png'
})

// Methods
const scrollToHowItWorks = () => {
  const element = document.querySelector('[data-how-it-works]')
  if (element) {
    element.scrollIntoView({ behavior: 'smooth' })
  }
}

const goToLogin = () => {
  // Emit event to parent component to trigger login modal
  const loginButton = document.querySelector('[data-login-button]')
  if (loginButton) {
    ;(loginButton as HTMLElement).click()
  }
}
</script>

<style scoped>
/* Custom styling for the comparison slider using CSS variables */
.custom-slider {
  --divider-width: 4px;
  --divider-color: #000000;
  --divider-shadow: 0px 0px 8px rgba(0, 0, 0, 0.3);
  --default-handle-opacity: 0; /* Hide default handle since we're using custom */
}

/* Hover effects */
.custom-slider:hover {
  --divider-shadow: 0px 0px 12px rgba(0, 0, 0, 0.5);
}

/* Custom handle styling */
.custom-handle {
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: grab;
  transition: all 0.2s ease;
  user-select: none;
}

.custom-handle:hover {
  transform: scale(1.1);
}

.custom-handle:active {
  cursor: grabbing;
  transform: scale(0.95);
}

/* Ensure images maintain aspect ratio */
img {
  display: block;
  width: 100%;
  height: auto;
  max-height: 600px;
  object-fit: contain;
}
</style>
